package com.med.backend.persistence.util;

public enum RolePermission {
    // ADMINISTRATOR
    FIND_ALL_USERS,

    // DOCTOR
    FIND_ALL_DOCTORS,
    CREATE_ONE_DOCTOR,
    UPDATE_ONE_DOCTOR,
    DELETE_ONE_DOCTOR,

    // RECEPTIONIST
    CREATE_ONE_RECEPTIONIST,
    UPDATE_ONE_RECEPTIONIST,
    DELETE_ONE_RECEPTIONIST,
    FIND_ALL_RECEPTIONISTS,

    // PATIENT
    CREATE_ONE_PATIENT,
    UPDATE_ONE_PATIENT,
    DELETE_ONE_PATIENT,
    FIND_ALL_PATIENTS,

    // SCHEDULE
    CREATE_ONE_SCHEDULE,
    UPDATE_ONE_SCHEDULE,
    DELETE_ONE_SCHEDULE,
    FIND_ALL_SCHEDULES,
    FIND_SCHEDULES_BY_DOCTOR,

    // APPOINTMENT
    CREATE_ONE_APPOINTMENT,
    UPDATE_ONE_APPOINTMENT,
    DELETE_ONE_APPOINTMENT,
    FIND_ALL_APPOINTMENTS,
    FIND_APPOINTMENTS_BY_PATIENT,
    FIND_APPOINTMENTS_BY_DOCTOR,

    // MEDICAL RECORD
    CREATE_ONE_MEDICAL_RECORD,
    UPDATE_ONE_MEDICAL_RECORD,
    DELETE_ONE_MEDICAL_RECORD,
    FIND_ALL_MEDICAL_RECORDS,
    FIND_MEDICAL_RECORDS_BY_PATIENT,
    FIND_MEDICAL_RECORD_BY_ID,

    // MEDICAL NOTE
    CREATE_ONE_MEDICAL_NOTE,
    UPDATE_ONE_MEDICAL_NOTE,
    DELETE_ONE_MEDICAL_NOTE,
    FIND_ALL_MEDICAL_NOTES,
    FIND_MEDICAL_NOTES_BY_MEDICAL_RECORD,
    FIND_MEDICAL_NOTE_BY_ID,

    // CONSULT
    CREATE_ONE_CONSULT,
    UPDATE_ONE_CONSULT,
    DELETE_ONE_CONSULT,
    FIND_ALL_CONSULTS,
    FIND_CONSULTS_BY_PATIENT,
    FIND_CONSULTS_BY_DOCTOR,

    // ALL
    READ_MY_PROFILE;
}
