package com.med.backend.persistence.util;

public enum RolePermission {
    // ADMINISTRATOR
    FIND_ALL_USERS,

    // DOCTOR
    FIND_ALL_DOCTORS,
    CREATE_ONE_DOCTOR,
    UPDATE_ONE_DOCTOR,
    DELETE_ONE_DOCTOR,

    // RECEPTIONIST
    CREATE_ONE_RECEPTIONIST,
    UPDATE_ONE_RECEPTIONIST,
    DELETE_ONE_RECEPTIONIST,
    FIND_ALL_RECEPTIONISTS,

    // PATIENT
    CREATE_ONE_PATIENT,
    UPDATE_ONE_PATIENT,
    DELETE_ONE_PATIENT,
    FIND_ALL_PATIENTS,

    // SCHEDULE
    CREATE_ONE_SCHEDULE,
    UPDATE_ONE_SCHEDULE,
    DELETE_ONE_SCHEDULE,
    FIND_ALL_SCHEDULES,
    FIND_SCHEDULES_BY_DOCTOR,

    // ALL
    READ_MY_PROFILE;
}
